services:
  postgres:
    image: 'postgres:16'
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=codeanalizer_db
      - POSTGRES_USER=codeanalizer
      - POSTGRES_PASSWORD=codeanalizer
      - POSTGRES_PORT=5432
    container_name: codeanalizer_db
    networks:
      - CodeAnalizer-Net

  python-app:
    image: 'codeanalizer_image'
    ports:
      - "8000:8000"
      - "8081:8081"
      - "5678:5678"
    volumes:
      - 'C:/Projects/CodeAnalizer:/opt'
    container_name: CodeAnalizer
    networks:
      - CodeAnalizer-Net
    depends_on:
      - postgres
    working_dir: /opt
    command: python -Xfrozen_modules=off -m debugpy --listen 0.0.0.0:5678 /opt/CodeAnalizer/manage.py runserver 0.0.0.0:8000

networks:
  CodeAnalizer-Net:
    external: false
